image: node:18-alpine

variables:
  NPM_CONFIG_UNSAFE_PERM: "true"

stages:
  - test
  - publish

before_script:
  - npm i

eslint:
  script: npx eslint --format gitlab .
  artifacts:
    reports:
      codequality: gl-codequality.json

jest:
  script: npx jest --coverage --reporters jest-junit
  artifacts:
    reports:
      junit: junit.xml

pack:
  script: npm pack

prettier:
  script: npx prettier --check .

publish:
  stage: publish
  only:
    - tags
  script:
    - npm config set //registry.npmjs.org/:_authToken "$NPM_TOKEN"
    - npm publish

tsc:
  script: npx tsc
